---
title: "Strategic brain connectivity"
author: "Kate Mills, Zdena Op de Macks, John Flournoy, Theresa Cheng & TDS team"
date: "September 27, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate","psych","corrplot")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Set working directory
```{r Set Directory, message=FALSE, warning=FALSE, include=FALSE}
getwd()
workdir=as.character(read.table((paste0(getwd(),"/org/workingdirectory.txt")))[[1]])
```

Extract rsfcMRI preprocessing stats
```{r Extract and plot run times, echo=TRUE}
# Set directory
rsfcMRI_subjects="/Volumes/TDS/bids_data/derivatives/rsfMRI_preproc_noFDscrub/"
# create sub list based on folders within the restings state fcMRI subjects folder
subs<-list.files(path = rsfcMRI_subjects, pattern = "sub")
# set scrubbing threshold
scrubbingThreshold=.2
# extract info
extract_rsfcMRI_runinfo= function(sub){
if (file.exists(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_enorm.1D"))){
      log<-read.csv(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_enorm.1D"))
      preproc_complete="yes"
      blurps<-nrow(log %>% filter(.[[1]]>scrubbingThreshold))
      potential<-(nrow(log)-(blurps*2))
      viable<-ifelse(potential>=385,"yes","no")
      cbind(sub,blurps,potential,viable,preproc_complete)
    } else{
      preproc_complete="no"
      blurps<-NA
      potential<-NA
      viable<-"no"
      cbind(sub,blurps,potential,viable,preproc_complete)
      }
}

outputlist<-lapply(subs,extract_rsfcMRI_runinfo)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(blurps=as.numeric(levels(blurps))[blurps],
         potential=as.numeric(levels(potential))[potential]) %>%
  mutate(potential=ifelse(potential<0,0,potential))

useable <- ggplot((output.df %>% select(-blurps)),
                aes(x=sub, y=(potential*.78)/60, fill=viable))
useable + geom_bar(colour="black", stat="identity") 

sublist<-output.df %>% 
  filter(viable=="yes") %>%
  select(sub)

print(paste0(nrow(sublist)," are viable"))
```

Exclude subs for various reasons
```{r}
sublist<- sublist %>%
  filter(!sub=="sub-192") %>% # sub needs timecourses extracted again
  filter(!sub=="sub-334")  # IQ lower than 70
```

Obtain demographic data
```{r}
# Females are 1 and Males are 0
redcapData <- read.csv(paste0(workdir,"Redcap/ages_at_sessions.csv"), header = TRUE, stringsAsFactors = FALSE) %>%
  mutate(gender=ifelse(gender==0,"M",
                       ifelse(gender==1,"F",
                              NA)),
         fsiq2=ifelse(is.na(fsiq2),999,fsiq2)) %>%
  filter(!sid==999) %>%
  filter(!fsiq2<70) %>% # exclude individuals with IQs less than 70
  mutate(fsiq2=ifelse(fsiq2==999,NA,fsiq2),
         sub=paste0("sub-",sid)) %>%
  mutate(group=ifelse(grepl("-3",sub),"foster",
                      ifelse(grepl("-4",sub),"jj",
                             ifelse(grepl("-1",sub),"community",NA))))%>%
  select(-sid) #%>%
  #filter(sub %in% sublist$sub)

print(paste0(length(unique(redcapData$sub))," participants w/ demographic data"))
print(paste0(length(unique((redcapData %>% filter(group=="community"))$sub))," community participants w/ demographic data"))
print(paste0(length(unique((redcapData %>% filter(group=="foster"))$sub))," CWS participants w/ demographic data"))

```

Obtain behavior data
```{r}
ylg_data<-read.csv(paste('/Volumes/TDS/behavior/YLG/processed/tds-all_trial_by_trial.csv',sep=''))

ylg <- ylg_data %>% 
  mutate(condition = ifelse(grepl('1|2', run_index), "Mock",
                     ifelse(grepl('3|4', run_index), "Alone",
                     ifelse(grepl('5|6', run_index), "Peer", 
                     ifelse(grepl('7|8', run_index), "Exclusion", NA))))) %>%
  mutate(time=run.time.ms/60000) %>%
  mutate(go = ifelse(decision=='GO', 1, 0)) %>%
  mutate(crash = ifelse(scenario=='CRASH', 1, 0)) %>%
  mutate(go_cr = ifelse(decision=='GO' & scenario=='CRASH', 1, 0)) %>%
  mutate(stop = ifelse(decision=='STOP', 1, 0)) %>%
  mutate(stop_nocar = ifelse(decision=='STOP' & scenario=='SAFE', 1, 0)) %>%
  mutate(event = ifelse(decision=='GO' & scenario=='SAFE', 1,
                 ifelse(decision=='GO' & scenario=='CRASH', 2,
                 ifelse(decision=='STOP' & scenario=='CROSSCAR', 3,
                 ifelse(decision=='STOP' & scenario=='SAFE', 4, NA))))) %>%
  mutate(count1 = ifelse(event==1, 1, 0)) %>%
  mutate(count2 = ifelse(event==2, 1, 0)) %>%
  mutate(count3 = ifelse(event==3, 1, 0)) %>%
  mutate(count4 = ifelse(event==4, 1, 0))

# Convert to factors
ylg$condition <- as.factor(ylg$condition)

# exclude people for behavioral issues
exclude = c(103, 107, 112, 138, 143, 176, 191)
ylg_filtered = ylg %>% 
  filter(!subject.name %in% exclude)

count_trials_per_sub<-ylg_filtered %>% group_by(subject.name) %>% summarize(n()) 

ylg_timing<-ylg_filtered %>%
  select(subject.name,run_index,time,condition) %>%
  distinct(subject.name,run_index,time,condition,.keep_all = TRUE) %>%
  mutate(group=ifelse(subject.name<300,"community",
                      ifelse((subject.name>299 & subject.name<400),"foster",
                             ifelse(subject.name>400,"jj",NA)))) %>%
  mutate(sub=paste0("sub-",as.factor(subject.name))) %>%
  select(-subject.name) %>%
  filter(!group=="jj") %>%
  filter(!sub=="sub-334") # IQ lower than 70
  #filter(sub %in% sublist$sub)

# Relevel condition
ylg_timing$condition = factor(ylg_timing$condition,levels(ylg_timing$condition)[c(3,1,4,2)])
print(levels(ylg_timing$condition))

print(paste0(length(unique(ylg_timing$sub))," participants w/ behavioral data"))
print(paste0(length(unique((ylg_timing %>% filter(group=="community"))$sub))," community participants w/ behavioral data"))
print(paste0(length(unique((ylg_timing %>% filter(group=="foster"))$sub))," CWS participants w/ behavioral data"))

```

See how the behavioral samples differ With ZDENA's awesome scripts
```{r}
# Join together behavioural and demographic data
ylg_timing<-left_join(x = ylg_timing,y= redcapData,by = c("group", "sub"))

hist_by_age_gender<-ylg_timing %>%
  distinct(sub, s2_age, gender, group,fsiq2)

#### Statistics #######
# Age by group (Zdena style)
age_by_group<-hist_by_age_gender %>%
  group_by(group) %>% 
  summarize(mean = mean(s2_age),
            sd = sd(s2_age), 
            min = min(s2_age, na.rm=T),
            max = max(s2_age, na.rm=T),
            n = n(), se = sd/sqrt(n),
            ci=qt(0.975, df=n-1)*se)
n_by_gender<-hist_by_age_gender %>% 
  group_by(group, gender) %>% 
  summarize(n=n())

# IQ by group (Zdena style)
iq_by_group<-hist_by_age_gender %>%
  group_by(group) %>% 
  summarize(mean = mean(fsiq2, na.rm=T), sd = sd(fsiq2, na.rm=T), 
            min = min(fsiq2, na.rm=T), max = max(fsiq2, na.rm=T),
            n = sum(!is.na(fsiq2)), se = sd/sqrt(n), ci=qt(0.975, df=n-1)*se)
n_by_gender<-hist_by_age_gender %>% 
  group_by(group, gender) %>% 
  summarize(sum(!is.na(fsiq2)))

age_ttest<-t.test(hist_by_age_gender$s2_age~hist_by_age_gender$group) 
iq_ttest<-t.test(hist_by_age_gender$fsiq2~hist_by_age_gender$group) 

# Get ACE data
qualtrics_folder<-paste(workdir,"Qualtrics/scoring_script_output/", sep='')
qualtrics2<-read.csv(paste(qualtrics_folder, 'TDS-2-auto_scored_scales_wide.csv', sep=''))
qualtrics1pre<-read.csv(paste(qualtrics_folder, 'TDS-1-PRE-auto_scored_scales_wide.csv', sep=''))
qualtrics1post<-read.csv(paste(qualtrics_folder, 'TDS-1-POST-auto_scored_scales_wide.csv', sep=''))
qualtrics_data<-bind_rows(qualtrics2, qualtrics1pre)
qualtrics_data<-bind_rows(qualtrics_data, qualtrics1post)

qualtrics_data<-qualtrics_data %>% 
  mutate(PDS_mean_score=ifelse(is.na(PDS_female_mean_score_score)==TRUE,
                                                                PDS_male_mean_score_score,
                                                                PDS_female_mean_score_score),
         sub=paste0("sub-",SID))
rm(qualtrics1post,qualtrics1pre,qualtrics2,qualtrics_folder)
         
# Merge Qualtrics with YLG and demographic data
qualtrics_data<-merge(hist_by_age_gender, qualtrics_data, by= 'sub') %>%
  mutate(ace_total=ACE_ace_total_score*10, ace_abuse=ACE_ace_abuse_score*3,
                      ace_neglect=ACE_ace_neglect_score*2, ace_maltreatment=ace_abuse+ace_neglect) %>%
  filter(!is.na(ace_total))

ace<-qualtrics_data %>% 
  group_by(group) %>%
  summarize(mean = mean(ace_total, na.rm=T), sd = sd(ace_total, na.rm=T),
            min = min(ace_total, na.rm=T), max = max(ace_total, na.rm=T),
            n = sum(!is.na(ace_total)), se = sd/sqrt(n), ci=qt(0.975, df=n-1)*se)
n_by_gender<-qualtrics_data %>% 
  group_by(group, gender) %>% 
  summarize(n=sum(!is.na(ace_total)))

t.test(qualtrics_data$ace_total~qualtrics_data$group) 
t.test(qualtrics_data$ace_maltreatment~qualtrics_data$group) 

  

##### Plots ######

# Make group labels
group_labels<-c("community"='Community', 
                "foster"="Child Welfare Services")

# Age by gender by group sampling density (Kate Style)
gender_age_group_density<-ggplot(hist_by_age_gender,
                          aes(x=s2_age, fill=gender)) + 
  xlab("Age") +
  geom_density(alpha=.3) +
  facet_grid(.~group,
             scales='free',
             labeller=as_labeller(group_labels))+
  scale_fill_manual(values=c('deeppink', 'dodgerblue'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="right")
gender_age_group_density
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/gender_age_group_density.png"),
#       plot=gender_age_group_density, width=6, height=5, units='in', dpi=300)


# Boxplots for demographics 
box_age_group<-ggplot(qualtrics_data,
       aes(x=group,
           y=s2_age,
           fill=group)) +
  geom_boxplot(aes(fill=group)) + 
  labs(y='Age', fill='Sample') +
  scale_fill_manual(values=c('maroon1', 'maroon4'),
                      labels=c('Community', 'Child Welfare Services'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x=element_blank(),
        panel.background = element_blank(),
        legend.position="right")
box_age_group
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/box_age_group.png"),
#       plot=box_age_group, width=6, height=5, units='in', dpi=300)

box_pds_group<-ggplot(qualtrics_data,
       aes(x=group,
           y=PDS_mean_score,
           fill=group)) +
  geom_boxplot(aes(fill=group)) + 
  labs(y='Pubertal development', fill='Sample') +
  scale_y_continuous(limits=c(1,4)) +
  scale_fill_manual(values=c('maroon1', 'maroon4'),
                      labels=c('Community', 'Child Welfare Services'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x=element_blank(),
        panel.background = element_blank(),
        legend.position="right")
box_pds_group
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/box_pds_group.png"),
#       plot=box_pds_group, width=6, height=5, units='in', dpi=300)

box_iq_group<-ggplot(qualtrics_data,
       aes(x=group,
           y=fsiq2,
           fill=group)) +
  geom_boxplot(aes(fill=group)) + 
  labs(y='IQ', fill='Sample') +
  scale_fill_manual(values=c('maroon1', 'maroon4'),
                      labels=c('Community', 'Child Welfare Services'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x=element_blank(),
        panel.background = element_blank(),
        legend.position="right")
box_iq_group
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/box_iq_group.png"),
#       plot=box_iq_group, width=6, height=5, units='in', dpi=300)

box_adversity_group<-ggplot(qualtrics_data,
       aes(x=group,
           y=ace_total,
           fill=group)) +
  geom_boxplot(aes(fill=group)) + 
  scale_y_continuous(breaks=c(0,5,10)) +
  labs(y='Adversity', fill='Sample') +
  scale_fill_manual(values=c('maroon1', 'maroon4'),
                      labels=c('Community', 'Child Welfare Services'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x=element_blank(),
        panel.background = element_blank(),
        legend.position="right")
box_adversity_group
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/box_adversity_group.png"),
#       plot=box_adversity_group, width=6, height=5, units='in', dpi=300)

box_maltreatment_group<-ggplot(qualtrics_data,
       aes(x=group,
           y=ace_maltreatment,
           fill=group)) +
  geom_boxplot(aes(fill=group)) + 
  labs(y='Maltreatment', fill='Sample') +
  scale_fill_manual(values=c('maroon1', 'maroon4'),
                      labels=c('Community', 'Child Welfare Services'))+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x=element_blank(),
        panel.background = element_blank(),
        legend.position="right")
box_maltreatment_group
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/box_maltreatment_group.png"),
#       plot=box_maltreatment_group, width=6, height=5, units='in', dpi=300)
```

Analyze behavior data
```{r}
######################
#### Graph it ########
### Time across 8 runs ###

group_colors <- c("community" = "maroon1", "foster" = "maroon4")

# Time plotted across all runs by SAMPLE
time.plot <-
  ylg_timing %>%
  group_by(group, condition, run_index) %>% 
  summarize(mean = mean(time),
            sd = sd(time),
            n = n(), 
            se = sd/sqrt(n),
            ci=qt(0.975, df=n-1)*se)

time_plot<-ggplot(time.plot,
                  aes(x=run_index, y=mean, color=group)) +
  geom_point(position=position_dodge(.1), size=3) +
  geom_line(aes(group=group), size=1) +
  geom_errorbar(aes(ymax=mean + ci, ymin=mean - ci),
                width=0.5,
                position=position_dodge(.2)) +
  #facet_grid(.~condition, scales='free') +
  labs(x='Run number', y='Run completion time\n(in minutes)', color='Sample') +
  scale_colour_manual(values=group_colors,
                      labels=group_labels)+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="bottom")
time_plot
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/time_by_runindex_group.png"),
#       plot=time_plot, width=7, height=5, units='in', dpi=300)


#################
#### Models #####
## Find best fitting polynomial model for learning across the course of the task
nullmodel=lme(time ~ 1, method="ML", random = ~1|sub, data=ylg_timing)
linmodel=lme(time ~ run_index, method="ML", random = ~1|sub, data=ylg_timing)
groupmodel=lme(time ~ group, method="ML", random = ~1|sub, data=ylg_timing)
lingroupmainmodel=lme(time ~ run_index+group, method="ML", random = ~1|sub, data=ylg_timing)
lingroupintmodel=lme(time ~ run_index*group, method="ML", random = ~1|sub, data=ylg_timing)

# Compare models with run index only
anova(nullmodel,linmodel,lingroupmainmodel,lingroupintmodel)

# Compare models with group only
anova(nullmodel,groupmodel,lingroupmainmodel,lingroupintmodel)

# best model incorporates both main effects of group and run index
summary(lingroupmainmodel)

# generate community sample models
commnullmodel=lme(time ~ 1, method="ML", random = ~1|sub, data=(ylg_timing %>%
                                                                    filter(group=="community")))
commmodel=lme(time ~ run_index, method="ML", random = ~1|sub, data=(ylg_timing %>%
                                                                    filter(group=="community")))
anova(commnullmodel,commmodel)
summary(commmodel)

# generate foster sample models
fosternullmodel=lme(time ~ 1, method="ML", random = ~1|sub, data=(ylg_timing %>%
                                                                    filter(group=="foster")))
fostermodel=lme(time ~ run_index, method="ML", random = ~1|sub, data=(ylg_timing %>%
                                                                    filter(group=="foster")))
anova(fosternullmodel,fostermodel)
summary(fostermodel)

# Predicted model
run_index<-seq(1:8)
comm.data.pred = cbind.data.frame(run_index)
y.pred = predict(commmodel,
                   comm.data.pred,
                   level=0)
comm.data.pred = cbind.data.frame(comm.data.pred,
                               y.pred)
scale = 1.96
designmat<-model.matrix(eval(eval(commmodel$call$fixed)[-2]),
                          comm.data.pred[-3]) #make design matrix
SDvalue<-sqrt(diag(designmat %*% commmodel$varFix %*% t(designmat))) #calculate standard deviation for each point for each model
y.lower<-y.pred-(scale*SDvalue) #calculate confidence intervals - lower
y.upper<-y.pred+(scale*SDvalue) #calculate confidence intervals - upper
comm.data.pred = cbind.data.frame(comm.data.pred,
                               y.lower,
                               y.upper)
comm.data.pred$time<-comm.data.pred$y.pred

foster.data.pred = cbind.data.frame(run_index)
y.pred = predict(fostermodel,
                   foster.data.pred,
                   level=0)
foster.data.pred = cbind.data.frame(foster.data.pred,
                               y.pred)
scale = 1.96
designmat<-model.matrix(eval(eval(fostermodel$call$fixed)[-2]),
                          foster.data.pred[-3]) #make design matrix
SDvalue<-sqrt(diag(designmat %*% fostermodel$varFix %*% t(designmat))) #calculate standard deviation for each point for each model
y.lower<-y.pred-(scale*SDvalue) #calculate confidence intervals - lower
y.upper<-y.pred+(scale*SDvalue) #calculate confidence intervals - upper
foster.data.pred = cbind.data.frame(foster.data.pred,
                               y.lower,
                               y.upper)
foster.data.pred$time<-foster.data.pred$y.pred

## Graph it yo!
group_colors <- c("community" = "maroon1", "foster" = "maroon4")

model_time_by_runindex<-ggplot(ylg_timing,
                         aes(y=time,
                             x=run_index))+
  geom_line(data=comm.data.pred,
              aes(x=run_index, y=time), size=1, colour="maroon1")+
  geom_ribbon(data=comm.data.pred,
              aes(ymin=y.lower, ymax=y.upper), alpha=0.4, fill="maroon1")+
  geom_line(data=foster.data.pred,
              aes(x=run_index, y=time), size=1, colour="maroon4")+
  geom_ribbon(data=foster.data.pred,
              aes(ymin=y.lower, ymax=y.upper), alpha=0.4, fill="maroon4")+
  geom_line(data=ylg_timing,
            aes(colour=group, group=sub),size=.2,alpha=0.2)+
  scale_fill_manual(values = group_colors)+
  scale_colour_manual(values = group_colors)+
  geom_point(data=ylg_timing,
             aes(colour=group, group=sub),size=1,alpha=0.2)+
   labs(x='Run number', y='Run completion time\n(in minutes)', color='Sample')+
  theme_bw() +
  theme_minimal(base_size = 20, base_family = "Arial") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="bottom")
model_time_by_runindex
ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/model_time_by_runindex.png"),
       plot=model_time_by_runindex, width=7, height=5, units='in', dpi=300)


###################################################################

## Check out if condition impacts time to complete run
condition_model=lme(time ~ condition, method="ML", random = ~1|sub, data=ylg_timing)
condition_group_model=lme(time ~ condition+group, method="ML", random = ~1|sub, data=ylg_timing)
condition_intgroup_model=lme(time ~ condition*group, method="ML", random = ~1|sub, data=ylg_timing)
anova(condition_model,condition_group_model,condition_intgroup_model)
# time to complete run varies between conditions by groups in different ways
summary(condition_group_model)

condition_runindex_model=lme(time ~ condition+run_index, method="ML", random = ~1|sub, data=ylg_timing)
condition_intrunindex_model=lme(time ~ condition*run_index, method="ML", random = ~1|sub, data=ylg_timing)
condition_intrunindex_group_model=lme(time ~ condition*run_index+group, method="ML", random = ~1|sub, data=ylg_timing)
condition_intrunindex_intgroup_model=lme(time ~ condition*run_index*group, method="ML", random = ~1|sub, data=ylg_timing)
anova(nullmodel,condition_model,condition_runindex_model,
      condition_intrunindex_model,condition_intrunindex_group_model,
      condition_intrunindex_intgroup_model)
anova(nullmodel,linmodel)

# best model takes into account the main effects of condition, run index, and group
summary(condition_intrunindex_group_model)
```

Get timecourses
```{r timecourses}
# Set fixed variables
numcores<-detectCores()[1]
scrubbingThreshold<-.2
sub_base_dir="/Volumes/TDS/bids_data/derivatives/rsfMRI_preproc_noFDscrub/"
parcellation_list_dir='/projects/dsnlab/TDS/TDS_scripts/sMRI/templates/lists/'
 
### John's dplyred timecourse extraction + clean function
 collectAndCorTimecourses <- function(sub, parcels, scrubbingThreshold, sub_base_dir) {
    #below makes a df with every parcel file location, that then reads in the data from that parcel.
    #result is a long data frame with indexes within each parcel (e.g. volume number 1:514)
    timecourses <- data.frame(file_location=paste0(sub_base_dir,sub,"/",sub,".results/timecourses/",sub,'_',parcels$parcel_name,'.txt'),
                              sub=sub,
                              parcel=parcels$parcel_name,
                              stringsAsFactors=F) %>%
      group_by(sub,parcel) %>% do({
        timecourse<-try(fread(.$file_location, stringsAsFactors=F))
        if('try-error' %in% class(timecourse)) timecourse <- data.frame(NA)
        timecourse
      }) %>%
      mutate(index=1:n()) %>% filter(!is.na(V1))
    sub_dir <- paste0(sub_base_dir,sub,"/",sub,".results/")
    #get the motion information and censor properly
    fdfile <- data.frame(motion=read.table(paste0(sub_dir,"motion_",sub,"_enorm.1D"))$V1) %>%
      mutate(index=1:n(),
             censor_raw=motion>scrubbingThreshold, #censor if over the threshold
             censor_1after=censor_raw | lag(censor_raw,1, default=F), #censor 1 after any censored vols
             censor=censor_1after | (lead(censor_1after,1, default=F) & lag(censor_1after,1, default=F))) #censor any vols between censored vols
    #timecourse length == motion data length error checking
    fdlength <- dim(fdfile)[1]
    nada <- timecourses %>% group_by(parcel) %>%
      summarize(n=n()) %>% group_by(parcel) %>%
      do(thing=if(.$n != fdlength) stop(paste0('fdfile and timecourse ARE NOT SAME LENGTH!!!',
                                               sub, ' ', .$parcel, '\n')))
    #get a summary of motion for filtering later, and just for our info
    motiondata <- summarize(fdfile,
                            Blurps=sum(censor_raw),
                            Numcensored=sum(censor))
    #remove censored volumes
    timecourses_censored <- left_join(timecourses, select(fdfile,index,censor)) %>% filter(!censor)
    #more summary info for filtering subjects later
    motiondata$Framesremaining <- timecourses_censored %>% group_by(parcel) %>% 
      summarize(frames_remaining=n()) %>% distinct(frames_remaining) %>%
      unlist  
    #make the timecourse data nice for correlations
    timecourses_censored_w <- timecourses_censored %>% 
      select(sub, index, parcel, V1) %>% 
      spread(parcel,V1) %>% ungroup %>% select(-index, -sub)
    #correlate!
    #CorrelationMatrix<-cor(timecourses_censored_w)
    CorrelationMatrix<-fisherz(cor(timecourses_censored_w))
    #just take the bottom triangle
    CorrelationMatrix[upper.tri(CorrelationMatrix, diag=TRUE)] <- NA
    #this gets the names for the rows and columns and assigns each cor value
    #a name that is the combination of the row and column.
    CorrDF <- as.data.frame(CorrelationMatrix) %>% #matrix colnames become df column names
      mutate(var2=rownames(CorrelationMatrix)) %>% #add a column for matrix row names
      gather(var1, cor, -var2) %>% #make wide cor mat long, but keep indexed by matrix row name
      filter(!is.na(cor)) %>% #remove NA (upper tri) rows
      unite(coi, var1, var2) #unite the row and col names, now next to each other, into a single name.
    ## The CorrDF data frame now looks like, for example:
    # key                         cor
    # ---                         -----
    # lh.Parcel_1_lh.Parcel_10    0.338
    ##
    # now we want to add in our summary timecourse info re motion etc, so we just 
    # add columns to the correlation data frame, and turn it into a data table for
    # efficiency later on.
    subjDF <- CorrDF %>% mutate(sub=sub, 
                                Blurps=motiondata$Blurps,
                                Numcensored=motiondata$Numcensored,
                                Framesremaining=motiondata$Framesremaining) %>% as.data.table
    }
 
## Extract Gordon timecourses ##
if(!file.exists("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Gordon_noWBVR_FishersZ_coisDT.RDS")){
  gordon_lhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"lhlabels.txt"))[[1]]) %>%
    filter(grepl("lh.Parcel", .[[1]]))%>%
    mutate(parcel_name=.[[1]]) %>%
    select(parcel_name)
  gordon_rhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"rhlabels.txt"))[[1]]) %>%
    filter(grepl("rh.Parcel", .[[1]]))%>%
    mutate(parcel_name=.[[1]]) %>%
    select(parcel_name)
  subcortical<-as.data.frame(c("aseg_26","aseg_58","aseg_18","aseg_54", 
                 "aseg_11","aseg_12","aseg_13","aseg_50",
                 "aseg_51","aseg_52","aseg_53","aseg_17")) %>%
    mutate(parcel_name=.[[1]]) %>%
    select(parcel_name)
  gordon<-bind_rows(gordon_rhparcels,gordon_lhparcels)
  gordon_subcortical<-bind_rows(gordon,subcortical)

  system.time(gordon_cois<- mclapply(as.list(as.character(sublist$sub)),
                                     collectAndCorTimecourses, 
                                     parcels=gordon_subcortical,
                                     scrubbingThreshold=scrubbingThreshold, 
                                     sub_base_dir=sub_base_dir,
                                     mc.cores=numcores))
  print(object.size(gordon_cois), quote = FALSE, units = "Mb")
  
  # bind list of data.tables into one long data.table and filter by frames remaining (< 5 mins)
  system.time(gordon_coisDT <- do.call(bind_rows, gordon_cois) %>% 
                filter(Framesremaining >= 385) %>%
                select(-Blurps, -Numcensored, -Framesremaining) %>%  
                as.data.table)
  system.time(sub_motion <- do.call(bind_rows, gordon_cois) %>%
                select(sub, Blurps, Numcensored, Framesremaining) %>% 
                distinct(sub, Blurps, Numcensored, Framesremaining, .keep_all = FALSE) %>%
                as.data.table)
  print(object.size(gordon_coisDT), quote = FALSE, units = "Mb")
  rm(gordon_cois);gc() #remove list, and garbage collect
  save(gordon_coisDT,file = "/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Gordon_noWBVR_FishersZ_coisDT.RDS")
  save(sub_motion,file = "/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/sub_motion.RDS")
} else {
  load(file = "/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Gordon_noWBVR_FishersZ_coisDT.RDS")
}


## Social Brain + NAcc parcels
if(!file.exists("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Social_noWBVR_FishersZ_coisDT.RDS")){
  socrois<-c("aseg_26","aseg_58",
             "lh.posterior-superior-temporal-sulcus","rh.posterior-superior-temporal-sulcus",
             "lh.temporal-parietal-junction-p","rh.temporal-parietal-junction-p",
             "lh.anterior-temporal-cortex","rh.anterior-temporal-cortex",
             "lh.Brodmann-10-medial","rh.Brodmann-10-medial",
             "lh.Parcel_1","rh.Parcel_162")
  socroinames<-c("l_nacc","r_nacc",
                 "l_psts","r_psts",
                 "l_tpj","r_tpj",
                 "l_atc","r_atc",
                 "l_mBA10","r_mBA10",
                 "l_precuneus","r_precuneus")

  socialbrain_parcels <- data.frame(parcel_name=socrois, stringsAsFactors=F)

  system.time(social_cois<- mclapply(as.list(as.character(sublist$sub)),
                                     collectAndCorTimecourses, 
                                     parcels=socialbrain_parcels,
                                     scrubbingThreshold=scrubbingThreshold, 
                                     sub_base_dir=sub_base_dir,
                                     mc.cores=numcores))
  print(object.size(social_cois), quote = FALSE, units = "Mb")
  
  # bind list of data.tables into one long data.table and filter by frames remaining (< 5 mins)
  system.time(social_coisDT <- do.call(bind_rows, social_cois) %>% 
                filter(Framesremaining >= 385) %>%
                select(-Blurps, -Numcensored, -Framesremaining) %>%  
                as.data.table)
  print(object.size(social_coisDT), quote = FALSE, units = "Mb")
  rm(social_cois);gc() #remove list, and garbage collect
  save(social_coisDT,file = "/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Social_noWBVR_FishersZ_coisDT.RDS")
} else {
  load(file = "/Volumes/TDS/bids_data/derivatives/strategic_connectivity/connectivity_data/Social_noWBVR_FishersZ_coisDT.RDS")
}
```

Analysis
```{r}
run_group_differences=FALSE
run_strategy=FALSE
run_condition=TRUE

gordon_cois<-distinct(gordon_coisDT, coi)
social_cois<-distinct(social_coisDT, coi)

## Group Differences ##
if(run_group_differences){
  # Identify parcels where connectivity differs by group membership
  system.time(
    social_groupdiff_models<-mclapply(X=as.character(as.list(social_cois$coi)), 
                                      demodata=ylg_timing,
                                      coidat=social_coisDT,
                                      mc.cores=numcores,
                                      FUN=function(coi_name, demodata, coidat){
                                        adf<-merge(as.data.table(filter(coidat,coi==coi_name)),
                                                   demodata,
                                                   by='sub',
                                                   allow.cartesian=T)
                                        group_mod=(lme(time ~ group,
                                                       method="ML",
                                                       random = ~1|sub,
                                                       data=adf))
                                        group_coi_mod=(lme(time ~ group+coi,
                                                           method="ML",
                                                           random = ~1|sub,
                                                           data=adf))
                                        group_coi_intmod=(lme(time ~ group*coi,
                                                              method="ML",
                                                              random = ~1|sub,
                                                              data=adf))
                                        mod_comp<-anova(group_mod,group_coi_mod,group_coi_intmod)
                                        if (mod_comp$'p-value'[3]<.05 &
                                            mod_comp$AIC[3]<mod_comp$AIC[2] &
                                            mod_comp$AIC[3]<mod_comp$AIC[1]){
                                          coiname<- as.character(coi_name)
                                          chisq <- round(mod_comp[2,8],2)
                                          pval <- round(mod_comp[2,9],4)
                                          AIC <- round(mod_comp[2,4],2)
                                          nullAIC <- round(mod_comp[1,4],2)
                                          mod_type <- "coi int model"
                                          retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                          retDF<-as.data.table(retDF)
                                        } else if (mod_comp$'p-value'[2]<.05 &
                                                   mod_comp$AIC[2]<mod_comp$AIC[1]){
                                          coiname <- as.character(coi_name)
                                          chisq <- round(mod_comp[2,8],2)
                                          pval <- round(mod_comp[2,9],4)
                                          AIC <- round(mod_comp[2,4],2)
                                          nullAIC <- round(mod_comp[1,4],2)
                                          mod_type <- "coi main model"
                                          retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                          retDF <- as.data.table(retDF)
                                        } else {
                                          coiname <- as.character(coi_name)
                                          chisq <- round(mod_comp[2,8],2)
                                          pval <- round(mod_comp[2,9],4)
                                          AIC <- round(mod_comp[2,4],2)
                                          nullAIC <- round(mod_comp[1,4],2)
                                          mod_type <- NA
                                          retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                          as.data.table(retDF)
                                        }
                                      }
    ))
  print(object.size(social_groupdiff_models), units='Mb')
  social_groupdiff_modelsDT <- rbindlist(social_groupdiff_models) #make this into a dataframe
  print(object.size(social_groupdiff_modelsDT), units='Mb')
  rm(social_groupdiff_models);gc()
  save(social_groupdiff_modelsDT, file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/social_groupdiff_modelsDT.RDS"))
} else {
  social_groupdiff_modelsDT<-load(file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/social_groupdiff_modelsDT.RDS"))
}

## Strategy: Time by run index ##
if(run_strategy){
  system.time(
    strategy_models<-mclapply(X=as.character(as.list(gordon_cois$coi)), 
                              demodata=ylg_timing,
                              coidat=gordon_coisDT,
                              mc.cores=numcores,
                              FUN=function(coi_name, demodata, coidat){
                                adf<-merge(as.data.table(filter(coidat,coi==coi_name)),
                                           demodata,
                                           by='sub',
                                           allow.cartesian=T)
                                beh_mod=lme(time ~ run_index+group,
                                            method="ML",
                                            random = ~1|sub,
                                            data=adf)
                                coi_mod=lme(time ~ run_index+group+cor,
                                            method="ML",
                                            random = ~1|sub,
                                            data=adf)
                                coi_int_mod=lme(time ~ run_index+group*cor,
                                                method="ML",
                                                random = ~1|sub,
                                                data=adf)
                                mod_comp<-anova(beh_mod,coi_mod,coi_int_mod)
                                if (mod_comp$'p-value'[3]<.05 &
                                    mod_comp$AIC[3]<mod_comp$AIC[2] &
                                    mod_comp$AIC[3]<mod_comp$AIC[1]){
                                  coiname<- as.character(coi_name)
                                  chisq <- round(mod_comp[3,8],2)
                                  pval <- round(mod_comp[3,9],4)
                                  AIC <- round(mod_comp[3,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- "coi int model"
                                  retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  retDF<-as.data.table(retDF)
                                } else if (mod_comp$'p-value'[2]<.05 &
                                           mod_comp$AIC[2]<mod_comp$AIC[1]){
                                  coiname <- as.character(coi_name)
                                  chisq <- round(mod_comp[2,8],2)
                                  pval <- round(mod_comp[2,9],4)
                                  AIC <- round(mod_comp[2,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- "coi main model"
                                  retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  retDF <- as.data.table(retDF)
                                } else {
                                  coiname <- as.character(coi_name)
                                  chisq <- round(mod_comp[2,8],2)
                                  pval <- round(mod_comp[2,9],4)
                                  AIC <- round(mod_comp[2,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- NA
                                  retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  as.data.table(retDF)
                                }
                              }
    ))
  print(object.size(strategy_models), units='Mb')
  strategy_modelsDT <- rbindlist(strategy_models) #make this into a dataframe
  print(object.size(strategy_modelsDT), units='Mb')
  rm(strategy_models);gc()
  save(strategy_modelsDT, file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                                     "connectivity_models/strategymodels_DT.RDS"))
} else {
  load(file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                    "connectivity_models/strategymodels_DT.RDS"))
}

## Strategy: Time by condition ##
if(run_condition){
  system.time(
    condition_models<-mclapply(X=as.character(as.list(social_cois$coi)), 
                              demodata=ylg_timing,
                              coidat=social_coisDT,
                              mc.cores=numcores,
                              FUN=function(coi_name, demodata, coidat){
                                adf<-merge(as.data.table(filter(coidat,coi==coi_name)),
                                           demodata,
                                           by='sub',
                                           allow.cartesian=T)
                                beh_mod=lme(time ~ run_index*condition+group,
                                            method="ML",
                                            random = ~1|sub,
                                            data=adf)
                                coi_mod=lme(time ~ run_index*condition+group+cor,
                                            method="ML",
                                            random = ~1|sub,
                                            data=adf)
                                coi_int_mod=lme(time ~ run_index*condition+group*cor,
                                                method="ML",
                                                random = ~1|sub,
                                                data=adf)
                                mod_comp<-anova(beh_mod,coi_mod,coi_int_mod)
                                if (mod_comp$'p-value'[3]<.05 &
                                    mod_comp$AIC[3]<mod_comp$AIC[2] &
                                    mod_comp$AIC[3]<mod_comp$AIC[1]){
                                  coiname<- as.character(coi_name)
                                  chisq <- round(mod_comp[3,8],2)
                                  pval <- round(mod_comp[3,9],4)
                                  AIC <- round(mod_comp[3,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- "coi int model"
                                  retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  retDF<-as.data.table(retDF)
                                } else if (mod_comp$'p-value'[2]<.05 &
                                           mod_comp$AIC[2]<mod_comp$AIC[1]){
                                  coiname <- as.character(coi_name)
                                  chisq <- round(mod_comp[2,8],2)
                                  pval <- round(mod_comp[2,9],4)
                                  AIC <- round(mod_comp[2,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- "coi main model"
                                  retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  retDF <- as.data.table(retDF)
                                } else {
                                  coiname <- as.character(coi_name)
                                  chisq <- round(mod_comp[2,8],2)
                                  pval <- round(mod_comp[2,9],4)
                                  AIC <- round(mod_comp[2,4],2)
                                  nullAIC <- round(mod_comp[1,4],2)
                                  mod_type <- NA
                                  retDF <- cbind(coiname,chisq,pval,AIC,nullAIC,mod_type)
                                  as.data.table(retDF)
                                }
                              }
    ))
  print(object.size(condition_models), units='Mb')
  condition_modelsDT <- rbindlist(condition_models) #make this into a dataframe
  print(object.size(condition_modelsDT), units='Mb')
  rm(condition_models);gc()
  save(condition_modelsDT, file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                                     "connectivity_models/condition_models_DT.RDS"))
} else {
  load(file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                    "connectivity_models/condition_models_DT.RDS"))
}

```

Unpack strategy models
```{r}
redoprepheat=FALSE

load(file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                    "connectivity_models/strategymodels_DT.RDS"))

strategy_modelsDT<-strategy_modelsDT %>%
  mutate(seed=ifelse(grepl("aseg",substring(coiname,0,7)),substring(coiname, 0, 7),substring(coiname, 0, 13)),
         target=ifelse(nchar(coiname)==15,substring(coiname,9,15),coiname))%>%
  mutate(target=ifelse(grepl("aseg",substring(coiname,0,4)),substring(coiname,9,length(coiname)),substring(coiname, 13, length(coiname)))) %>%
  mutate(target=ifelse(grepl("0_rh.",target),
                       substring(target, 3, length(target)),
                       ifelse(grepl("0_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("1_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("1_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("2_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("2_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("3_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("3_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("4_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("4_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("5_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("5_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("6_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("6_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("7_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("7_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("8_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("8_lh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("9_rh.",target),
                              substring(target, 3, length(target)),
                        ifelse(grepl("9_lh.",target),
                              substring(target, 3, length(target)),
                              target))))))))))))))))))))) %>%
  mutate(target=ifelse(grepl("_lh.",target),
                       substring(target, 2, length(target)),
                       ifelse(grepl("_rh.",target),
                              substring(target, 2, length(target)),target))) %>%
  mutate(seed=ifelse(grepl("_l",seed),
                     substring(seed,0,11),
                     ifelse(grepl("_r",seed),
                     substring(seed,0,11),
                     ifelse(substring(seed, nchar(seed))=="_",
                     substring(seed,0,12),seed))))

# Make sure the coi names are correct
unique(strategy_modelsDT$seed)
unique(strategy_modelsDT$target)

# See how many connections between/within networks were significant
parcel_key=read.csv(paste0("./gordon_subcortical_parcel_key.csv"))

if(redoprepheat){
  prepheat<-strategy_modelsDT %>%
    select(mod_type, seed, target,coiname,chisq,pval,AIC,nullAIC)
  prepheat<-left_join(prepheat, (parcel_key %>%
                                   mutate(seed=parcel_name) %>%
                                   select(seed,Community)),
                      by="seed") %>%
    mutate(seed_community=Community)%>%
    select(-Community)
  prepheat<-left_join(prepheat, (parcel_key %>%
                                   mutate(target=parcel_name) %>%
                                   select(target,Community)),
                      by="target") %>%
    mutate(target_community=Community) %>%
    select(-Community,-seed,-target) %>%
    mutate(connection=paste(seed_community,"_",target_community),
           model=ifelse(!is.na(mod_type),1,0)) 
  
  count_connections<-prepheat %>% 
    group_by(connection) %>% summarize(n()) 
  write.csv(count_connections,file = paste0(workdir,"../bids_data/derivatives/strategic_connectivity/tables/",
                                            "connection_count.csv"))
  count_sig_connections<-prepheat %>% 
    filter(!is.na(mod_type)) %>%
    group_by(connection) %>% summarize(n()) 
  
  write.csv(count_sig_connections,file = paste0(workdir,"../bids_data/derivatives/strategic_connectivity/tables/",
                                                "sig_connection_count.csv"))
}

# Make a heat map YO!
prepheat<-read.csv(file=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/tables/",
                                          "strategy_heatmap.csv"),header=TRUE,stringsAsFactors = FALSE)

strategy_heatmap<-ggplot(data = prepheat,
       aes(x=seed_community, y=target_community, fill=ratio)) + 
  scale_fill_distiller(palette = "RdPu")+
  geom_tile()+
  theme_minimal()+ 
 theme(
  axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1),
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank())+
 coord_fixed()
#ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/strategy_corrmatrix.png"),
#       plot=strategy_heatmap, width=6, height=5, units='in', dpi=300)

## Make example graph
coi_name="lh.Parcel_71_rh.Parcel_173" # 

demodata=ylg_timing
coidat=gordon_coisDT
adf<-merge(as.data.table(filter(coidat,coi==coi_name)),
                                           demodata,
                                           by='sub',
                                           allow.cartesian=T)

commmodel=lme(time ~ run_index*cor, method="ML", random = ~1|sub, data=(adf %>%
                                                                    filter(group=="community")))
summary(commmodel)
fostermodel=lme(time ~ run_index*cor, method="ML", random = ~1|sub, data=(adf %>%
                                                                    filter(group=="foster")))
summary(fostermodel)

# Predicted model
cor=seq((mean(adf$cor)-sd(adf$cor)),
            (mean(adf$cor)+sd(adf$cor)),
            length.out = 3)

corcomm=seq((mean((adf %>% filter(group=="community"))$cor)-sd((adf %>% filter(group=="community"))$cor)),
            (mean((adf %>% filter(group=="community"))$cor)+sd((adf %>% filter(group=="community"))$cor)),
            length.out = 3)

corfoster=seq((mean((adf %>% filter(group=="foster"))$cor)-sd((adf %>% filter(group=="foster"))$cor)),
            (mean((adf %>% filter(group=="foster"))$cor)+sd((adf %>% filter(group=="foster"))$cor)),
            length.out = 3)


    assign(paste0("comm_graphs"),
           lapply(X=cor,
                  FUN=function(COR){
             assign(paste0("frame",COR),
                    data.frame(run_index=run_index,
                               cor=COR))
             assign(paste0("frame",COR,"predvalue"),
                    predict(commmodel, get(paste0("frame",COR)), level=0))
             assign(paste0("designmat",COR),
                    model.matrix(eval(eval(commmodel$call$fixed)[-2]),
                                 get(paste0("frame",COR))[-3]))
             assign(paste0("frame",COR,"SDvalue"),
                    sqrt(diag(get(paste0("designmat",COR)) 
                              %*% commmodel$varFix 
                              %*% t(get(paste0("designmat",COR)))))) 
             assign("lowerCIvalue",
                    (get(paste0("frame",COR,"predvalue"))-
                       (1.96*get(paste0("frame",COR,"SDvalue")))))
            assign("upperCIvalue",
                   (get(paste0("frame",COR,"predvalue"))+
                      (1.96*get(paste0("frame",COR,"SDvalue")))))
             assign("time",
                    get(paste0("frame",COR,"predvalue")))
             cbind(get(paste0("frame",COR)),
                   time,
                   upperCIvalue,
                   lowerCIvalue,
                   run_index)
           }))
    
    assign(paste0("foster_graphs"),
           lapply(X=cor,
                  FUN=function(COR){
             assign(paste0("frame",COR),
                    data.frame(run_index=run_index,
                               cor=COR))
             assign(paste0("frame",COR,"predvalue"),
                    predict(fostermodel, get(paste0("frame",COR)), level=0))
             assign(paste0("designmat",COR),
                    model.matrix(eval(eval(fostermodel$call$fixed)[-2]),
                                 get(paste0("frame",COR))[-3]))
             assign(paste0("frame",COR,"SDvalue"),
                    sqrt(diag(get(paste0("designmat",COR)) 
                              %*% fostermodel$varFix 
                              %*% t(get(paste0("designmat",COR)))))) 
             assign("lowerCIvalue",
                    (get(paste0("frame",COR,"predvalue"))-
                       (1.96*get(paste0("frame",COR,"SDvalue")))))
            assign("upperCIvalue",
                   (get(paste0("frame",COR,"predvalue"))+
                      (1.96*get(paste0("frame",COR,"SDvalue")))))
             assign("time",
                    get(paste0("frame",COR,"predvalue")))
             cbind(get(paste0("frame",COR)),
                   time,
                   upperCIvalue,
                   lowerCIvalue,
                   run_index)
           }))
    
    assign(paste0("community_coi_graph"),
           ggplot(data=NULL,
                  aes(x=run_index,
                      y=time)) +
             ylim(2,3)+
             labs(x='Run number', y='Run completion time\n(in minutes)', color='Sample') +
             geom_line(data=(adf %>% filter(group=="community")),
                       aes(group=sub),size=.2,alpha=0.1, colour="maroon1")+
             geom_point(data=(adf %>% filter(group=="community")),
                        aes(group=sub),size=.7,alpha=0.1, colour="maroon1")+
           geom_line(data=as.data.frame(comm_graphs[[1]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink") +
             geom_ribbon(data=as.data.frame(comm_graphs[[1]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink") +
           geom_line(data=as.data.frame(comm_graphs[[2]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink3") +
             geom_ribbon(data=as.data.frame(comm_graphs[[2]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink3") +
                        geom_line(data=as.data.frame(comm_graphs[[3]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink4") +
             geom_ribbon(data=as.data.frame(comm_graphs[[3]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink4") +
             theme_bw() +
             theme_minimal(base_size = 12, base_family = "Arial") +
             theme(axis.line.x = element_line(colour = "black", size=.5),
                   axis.line.y = element_line(colour = "black", size=.5),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   panel.border = element_blank(),
                   panel.background = element_blank(),
                   legend.position="none"))
           get(paste0("community_coi_graph"))
ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/community_coi_graph.png"),
       plot=community_coi_graph, width=6, height=5, units='in', dpi=300)


assign(paste0("foster_coi_graph"),
           ggplot(data=NULL,
                  aes(x=run_index,
                      y=time)) +
             ylim(2,3)+
             labs(x='Run number', y='Run completion time\n(in minutes)', color='Sample') +
             geom_line(data=(adf %>% filter(group=="foster")),
                       aes(group=sub),size=.2,alpha=0.1, colour="maroon4")+
             geom_point(data=(adf %>% filter(group=="foster")),
                        aes(group=sub),size=.7,alpha=0.1, colour="maroon4")+
           geom_line(data=as.data.frame(foster_graphs[[1]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink") +
             geom_ribbon(data=as.data.frame(foster_graphs[[1]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink") +
           geom_line(data=as.data.frame(foster_graphs[[2]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink3") +
             geom_ribbon(data=as.data.frame(foster_graphs[[2]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink3") +
                        geom_line(data=as.data.frame(foster_graphs[[3]]),
                     aes(x=run_index,
                      y=time),
                     size=1,
                     colour="hotpink4") +
             geom_ribbon(data=as.data.frame(foster_graphs[[3]]),
                         aes(ymin=lowerCIvalue,
                             ymax=upperCIvalue),
                         alpha=0.2, fill="hotpink4") +
             theme_bw() +
             theme_minimal(base_size = 12, base_family = "Arial") +
             theme(axis.line.x = element_line(colour = "black", size=.5),
                   axis.line.y = element_line(colour = "black", size=.5),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   panel.border = element_blank(),
                   panel.background = element_blank(),
                   legend.position="none"))
           get(paste0("foster_coi_graph"))
ggsave(filename=paste0(workdir,"../bids_data/derivatives/strategic_connectivity/graphs/foster_coi_graph.png"),
       plot=foster_coi_graph, width=6, height=5, units='in', dpi=300)


```


Time by condition effects
```{r}
load(file= paste0("/Volumes/TDS/bids_data/derivatives/strategic_connectivity/",
                    "connectivity_models/condition_models_DT.RDS"))


```

Theresa Scripts
```{r}

## Load Gordon parcel data
parcels=read.csv(paste0("./gordon_subcortical_parcel_key.csv"))
parcels$target=as.character(parcels$parcel_name)

## Match COI target with Gordon parcel #
strategy_modelsDT_matched<-left_join(strategy_modelsDT,
                                     parcels, by=c("target"))
# Display the Data

## generate a data frame to plot
strategy_modelsDT_matched$Community=as.character(strategy_modelsDT_matched$Community) # turn community type into a character
df_strategy_models= data.frame(cbind("target"=unlist(strategy_modelsDT_matched$target),
                                     "seed"=unlist(strategy_modelsDT_matched$seed),
                                     "mod_type"=unlist(strategy_modelsDT_matched$mod_type),
                                     "Community"=unlist(strategy_modelsDT_matched$Community))) 
df_strategy_models$Community=as.factor(df_strategy_models$Community) # turn community back into a factor

## Make a table 

# calculate percentages
tbl=group_by(df_strategy_models, seed, mod_type, Community) %>% tally %>% 
  spread(Community, n, fill = 0)
kable(tbl, format="pandoc")

tbl=group_by(df_strategy_models, seed, mod_type) %>% tally %>% 
  spread(seed, n, fill = 0)
kable(tbl, format="pandoc")

# Plot
df_strategy_models=filter(df_strategy_models, !is.na(mod_type)) # remove those best explained by the null model


```