---
title: "FreeSurfer Stats"
author: "Kate"
date: "26 April 2017"
output: html_document
---

# Begin script

Load required packages
```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo","dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Extract FreeSurfer preprocessing stats
```{r Extract and plot run times, echo=TRUE}
# Set directory
rsfcMRI_subjects="/Volumes/TDS/bids_data/derivatives/rsfMRI_preproc/"
# create sub list based on folders within the freesurfer subjects folder
subs<-list.files(path = rsfcMRI_subjects, pattern = "sub")
# extract info
extract_rsfcMRI_runinfo= function(sub){
  if (file.exists(paste0(rsfcMRI_subjects,sub,"/",sub,".results/out.ss_review.",sub,".txt"))){
    log<-read.csv(paste0(rsfcMRI_subjects,sub,"/",sub,".results/out.ss_review.",sub,".txt"))
    TRsleft<-log %>% filter(grepl("TRs total",.[[1]]))
    TRsleft<-as.character(TRsleft[2,1])
    TRsleft<-substring(TRsleft,first=29,last=(nchar(TRsleft)))
    TRscensored<-log %>% filter(grepl("TRs censored",.[[1]]))
    TRscensored<-as.character(TRscensored[[1]])
    TRscensored<-substring(TRscensored,first=29,last=(nchar(TRscensored)))
    preproc_complete="yes"
    cbind(sub,TRsleft,TRscensored,preproc_complete)
    } else if (file.exists(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_censor.1D"))){
      log<-read.csv(paste0(rsfcMRI_subjects,sub,"/",sub,".results/motion_",sub,"_censor.1D"))
      TRsleft<-nrow(log %>% filter(.[[1]]=="1"))
      TRscensored<-nrow(log %>% filter(.[[1]]=="0"))
      preproc_complete="no"
      cbind(sub,TRsleft,TRscensored,preproc_complete)
    } else{
      TRsleft<-NA
      TRscensored<-NA
      preproc_complete="no"
      cbind(sub,TRsleft,TRscensored,preproc_complete)
      }
}
outputlist<-lapply(subs,extract_rsfcMRI_runinfo)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(TRscensored=as.numeric(levels(TRscensored))[TRscensored],
         TRsleft=as.numeric(levels(TRsleft))[TRsleft])

censored <- ggplot((output.df %>% select(-TRsleft)),
                aes(x=sub, y=TRscensored, fill=preproc_complete))
censored + geom_bar(colour="black", stat="identity") 

TotalTRs <- ggplot((output.df %>% select(-TRscensored)),
                aes(x=sub, y=TRsleft, fill=preproc_complete))
TotalTRs + geom_bar(colour="black", stat="identity")

TRtime <- ggplot((output.df %>% select(-TRscensored)),
                aes(x=sub, y=(TRsleft*.78)/60, fill=preproc_complete))
TRtime + geom_bar(colour="black", stat="identity")
```
