---
title: "Cheng_SAP"
author: "Kate & Theresa AND JOHN"
date: "May 24, 2017"
output: html_document
---

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo", "dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate","psych")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```


Get behavioral data together
```{r}
# ACES
library("plyr")
## TDS1: This data is stored within pre- and post- files, relative to IRB approval of additional questionnaires
df1<-plyr::rbind.fill(read.csv("/Volumes/TDS/behavior/Qualtrics/TDS-1-PRE-auto_scored_scales_wide.csv", header=TRUE),
                      read.csv("/Volumes/TDS/behavior/Qualtrics/TDS-1-POST-auto_scored_scales_wide.csv", header=TRUE))
# load pre/post, remove blank rows, and merge
df1<-cbind(SID=df1$SID, select(df1,starts_with("ACE_ace_abuse")), select(df1,starts_with("ACE_ace_neglect")),
          select(df1,starts_with("ACE_ace_hh")), select(df1,starts_with("ACE_ace_hh")))
# subset relevant items: abuse, neglect, hh

## TDS2
df2<-read.csv("/Volumes/TDS/behavior/Qualtrics/TDS-2-auto_scored_scales_wide.csv", header=TRUE) # load data
df2<-cbind(SID=df2$SID, select(df2,starts_with("ACE_ace_abuse")),  select(df2,starts_with("ACE_ace_neglect")),
          select(df2,starts_with("ACE_ace_hh")), select(df2,starts_with("ACE_ace_hh"))) # subset relevant items: abuse, neglect, hh

## Data cleaning
df_aces<- rbind.fill(df1, df2) %>% filter(is.na(.$SID)==FALSE) # merge TDS1 and TDS2, remove NA rows

fn <- substr(df_aces$SID,1,1)
df_aces$group= ifelse(fn %in% "1", "comm", 
                      ifelse(fn %in% "3", "dhs",
                             "jj"))

demographicsDF<-df_aces %>%
  mutate(abuse=ACE_ace_abuse_score,
         neglect=ACE_ace_neglect_score,
         sub=paste0("sub-",SID)) %>%
  select(sub, abuse, neglect, group) %>%
  filter(!group=="jj") %>%
  filter(!is.na(abuse))
detach("package:plyr", unload=TRUE)
rm(df1,df2,df_aces)
```

Filter subs if needed
```{r}
preprocessedcomplete<- preprocessedcomplete %>%
  filter(!sub=="sub-116") %>%
  filter(!sub=="sub-192") %>%
  filter(!sub=="sub-348") %>%
  filter(!sub=="sub-363")
```

Get timecourses
```{r}
numcores<-detectCores()[1]
scrubbingThreshold<-.2
sub_base_dir="/Volumes/TDS/bids_data/derivatives/rsfMRI_preproc_noFDscrub/"
parcellation_list_dir='/projects/dsnlab/tds/TDS_scripts/sMRI/templates/lists/'
lhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"lhlabels.txt"))[[1]]) %>%
  filter(grepl("lh.Parcel", .[[1]]))%>%
  mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
rhparcels<-as.data.frame(read.table(paste0(parcellation_list_dir,"rhlabels.txt"))[[1]]) %>%
  filter(grepl("rh.Parcel", .[[1]]))%>%
  mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
# https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT
subcorticalparcels<-as.data.frame(rbind("aseg_18","aseg_54","aseg_17","aseg_53")) %>%
   mutate(parcel_name=.[[1]]) %>%
  select(parcel_name)
gordon<-bind_rows(subcorticalparcels,rhparcels,lhparcels)
  
# rsfcMRI_subjects="/Volumes/TDS/bids_data/derivatives/rsfMRI_preproc/"
# # create sub list based on folders within the freesurfer subjects folder
# subs<-list.files(path = rsfcMRI_subjects, pattern = "sub")

collectAndCorTimecourses <- function(sub, parcels, scrubbingThreshold, sub_base_dir) {
  #below makes a df with every parcel file location, that then reads in the data from that parcel.
  #result is a long data frame with indexes within each parcel (e.g. volume number 1:514)
  timecourses <- data.frame(file_location=paste0(sub_base_dir,sub,"/",sub,".results/timecourses/",sub,'_',parcels$parcel_name,'.txt'),
                            sub=sub,
                            parcel=parcels$parcel_name,
                            stringsAsFactors=F) %>%
    group_by(sub,parcel) %>% do({
      timecourse<-try(fread(.$file_location, stringsAsFactors=F))
      if('try-error' %in% class(timecourse)) timecourse <- data.frame(NA)
      timecourse
    }) %>%
    mutate(index=1:n()) %>% filter(!is.na(V1))
  sub_dir <- paste0(sub_base_dir,sub,"/",sub,".results/")
  #get the motion information and censor properly
  fdfile <- data.frame(motion=read.table(paste0(sub_dir,"motion_",sub,"_enorm.1D"))$V1) %>%
    mutate(index=1:n(),
           censor_raw=motion>scrubbingThreshold, #censor if over the threshold
           censor_1after=censor_raw | lag(censor_raw,1, default=F), #censor 1 after any censored vols
           censor=censor_1after | (lead(censor_1after,1, default=F) & lag(censor_1after,1, default=F))) #censor any vols between censored vols
  #timecourse length == motion data length error checking
  fdlength <- dim(fdfile)[1]
  nada <- timecourses %>% group_by(parcel) %>%
    summarize(n=n()) %>% group_by(parcel) %>%
    do(thing=if(.$n != fdlength) stop(paste0('fdfile and timecourse ARE NOT SAME LENGTH!!!',
                                             sub, ' ', .$parcel, '\n')))
  #get a summary of motion for filtering later, and just for our info
  motiondata <- summarize(fdfile,
                          Blurps=sum(censor_raw),
                          Numcensored=sum(censor))
  #remove censored volumes
  timecourses_censored <- left_join(timecourses, select(fdfile,index,censor)) %>% filter(!censor)
  #more summary info for filtering subjects later
  motiondata$Framesremaining <- timecourses_censored %>% group_by(parcel) %>% 
    summarize(frames_remaining=n()) %>% distinct(frames_remaining) %>%
    unlist  
  #make the timecourse data nice for correlations
  timecourses_censored_w <- timecourses_censored %>% 
    select(sub, index, parcel, V1) %>% 
    spread(parcel,V1) %>% ungroup %>% select(-index, -sub)
  #correlate!
  CorrelationMatrix<-fisherz(cor(timecourses_censored_w))
  #just take the bottom triangle
  CorrelationMatrix[upper.tri(CorrelationMatrix, diag=TRUE)] <- NA
  #this gets the names for the rows and columns and assigns each cor value
  #a name that is the combination of the row and column.
  CorrDF <- as.data.frame(CorrelationMatrix) %>% #matrix colnames become df column names
    mutate(var2=rownames(CorrelationMatrix)) %>% #add a column for matrix row names
    gather(var1, cor, -var2) %>% #make wide cor mat long, but keep indexed by matrix row name
    filter(!is.na(cor)) %>% #remove NA (upper tri) rows
    unite(coi, var1, var2) #unite the row and col names, now next to each other, into a single name.
  ## The CorrDF data frame now looks like, for example:
  # key                         cor
  # ---                         -----
  # lh.Parcel_1_lh.Parcel_10    0.338
  ##
  # now we want to add in our summary timecourse info re motion etc, so we just 
  # add columns to the correlation data frame, and turn it into a data table for
  # efficiency later on.
  subjDF <- CorrDF %>% mutate(sub=sub, 
                              Blurps=motiondata$Blurps,
                              Numcensored=motiondata$Numcensored,
                              Framesremaining=motiondata$Framesremaining) %>% as.data.table
  subjDF <- subjDF %>%
    filter(grepl("aseg", coi))
}

system.time(gordon_cois <- mclapply(as.list(preprocessedcomplete$sub),
                                    collectAndCorTimecourses, 
                                    parcels=gordon,
                                    scrubbingThreshold=scrubbingThreshold, 
                                    sub_base_dir=sub_base_dir,
                                    mc.cores=1))
print(object.size(gordon_cois), quote = FALSE, units = "Mb")

# bind list of data.tables into one long data.table and filter by frames remaining (< 5 mins)
system.time(gordon_coisDT <- do.call(bind_rows, gordon_cois) %>% 
              filter(Framesremaining >= 385) %>%
              select(-Blurps, -Numcensored, -Framesremaining) %>%  #we don't need these columns anymore
              as.data.table)
print(object.size(gordon_coisDT), quote = FALSE, units = "Mb") #much smaller than the list of data.tables
rm(gordon_cois);gc() #remove list, and garbage collect
save(gordon_coisDT,file = "/Volumes/TDS/bids_data/derivatives/Cheng_SAP/gordon_coisDT.RDS")
```


Analysis
```{r}
rerun_models=TRUE

gordon_cois<-distinct(gordon_coisDT, coi)

if(rerun_models){
  system.time(
    gordon_models<-mclapply(X=as.list(gordon_cois$coi[1:50]), 
      demodata=demographicsDF,
      coidat=gordon_coisDT,
      mc.cores=1,
      FUN=function(coi_name, demodata, coidat){
        adf<-merge(as.data.table(filter(coidat,coi==coi_name)),
                   demodata,
                   by='sub',
                   allow.cartesian=T)
        null_mod=(lme(cor ~ 1,
                      method="ML",
                      random = ~1|sub,
                      data=adf))
        neglect_mod=(lme(cor ~ neglect,
                         method="ML",
                         random = ~1|sub,
                         data=adf))
        neglect_abuse_main_mod=(lme(cor ~ neglect + abuse,
                                    method="ML",
                                    random = ~1|sub,
                                    data=adf))
        neglect_abuse_int_mod=(lme(cor ~ neglect * abuse,
                                   method="ML",
                                   random = ~1|sub,
                                   data=adf))
        mod_comp<-anova(null_mod,neglect_mod,neglect_abuse_main_mod,neglect_abuse_int_mod)
        if (mod_comp$'p-value'[4]<.05 &
            mod_comp$AIC[4]<mod_comp$AIC[3] &
            mod_comp$AIC[4]<mod_comp$AIC[2] &
            mod_comp$AIC[4]<mod_comp$AIC[1]){
          coiname<- as.character(coi_name)
          chisq <- mod_comp[4,8]
          pval <- round(mod_comp[4,9],4)
          AIC <- mod_comp[4,4]
          nullAIC <- mod_comp[1,4]
          mod <- list(neglect_abuse_main_mod)
          mod_type <- "neglect and abuse interaction model"
          cbind(coiname,chisq,pval,AIC,nullAIC,mod_type,mod)
          retDF<-as.data.table(retDF)
        } else if (mod_comp$'p-value'[3]<.05 &
                   mod_comp$AIC[3]<mod_comp$AIC[2] &
                   mod_comp$AIC[3]<mod_comp$AIC[1]) {
          coiname<- as.character(coi_name)
          chisq <- mod_comp[3,8]
          pval <- round(mod_comp[3,9],4)
          AIC <- mod_comp[3,4]
          nullAIC <- mod_comp[1,4]
          mod <- list(neglect_abuse_main_mod)
          mod_type <- "neglect and abuse main model"
          retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type,mod)
          as.data.table(retDF)
        } else if (mod_comp$'p-value'[2]<.05 &
                   mod_comp$AIC[2]<mod_comp$AIC[1]){
          coiname<- as.character(coi_name)
          chisq <- mod_comp[2,8]
          pval <- round(mod_comp[2,9],4)
          AIC <- mod_comp[2,4]
          nullAIC <- mod_comp[1,4]
          mod <- list(neglect_mod)
          mod_type <- "neglect only model"
          retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type,mod)
          as.data.table(retDF)
        } else {
          coiname= as.character(coi_name)
          chisq <- "NA"
          pval <- "NA"
          AIC <- "NA"
          nullAIC <- mod_comp[1,4]
          mod <- "NA"
          mod_type <- "null model"
          retDF<-cbind(coiname,chisq,pval,AIC,nullAIC,mod_type,mod)
          as.data.table(retDF)
        }
      }
    ))
  print(object.size(gordon_models), units='Mb')
  gordon_modelsDT <- bind_rows(gordon_models)
  print(object.size(gordon_modelsDT), units='Mb')
  rm(gordon_models);gc()
  saveRDS(gordon_modelsDT, paste0("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/gordon_modelsDT.RDS"))
} else {
  gordon_modelsDT <- readRDS(paste0("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/gordon_modelsDT.RDS"))
}
```