---
title: "network-stats"
author: "Theresa Cheng"
date: "October 15, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load required packages ##
packages <-  c("lme4", "nlme", "zoo", "plyr", "dplyr", "tidyr", "ggplot2", "knitr", "parallel", "data.table", "lubridate","psych", "wesanderson")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)

# set scientific notation off unless >6 digits
options(scipen=6) 

rm(list=ls())

gordon_modelsDT = readRDS("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/gordon_modelsDT_AIC.RDS") # BIC NOW
```

```{r id coi target networks, include=TRUE}

## identify COI seed
gordon_modelsDT$seed=gsub('(^\\w{4,9}_\\d{2,3})_.*','\\1',gordon_modelsDT$coiname)

## identify COI target
gordon_modelsDT$ParcelID= 
  ifelse(startsWith((gsub('aseg_\\d\\d_(.*)','\\1',gordon_modelsDT$coiname)), "aseg"), # if it starts with aseg
       gsub('aseg_\\d\\d_(aseg_\\d\\d)','\\1',gordon_modelsDT$coiname), # then call coitarget aseg_##
       gsub('aseg_\\d\\d_\\wh.Parcel_(.*)','\\1',gordon_modelsDT$coiname)) # but if not, coitarget is the Gordon parcel number

## Load Gordon parcel data
parcels=read.csv("/projects/dsnlab/tds/TDS_scripts/rsfMRI/Cheng_SAP/Parcels/Parcels.csv")
parcels$ParcelID=as.character(parcels$ParcelID)

## Match COI target with Gordon parcel #
gordon_modelsDT=merge(gordon_modelsDT, parcels, by="ParcelID", all.x=TRUE)

# Display the Data

## generate a data frame to plot
gordon_modelsDT$Community=as.character(gordon_modelsDT$Community) # turn community type into a character
df_gordon_models= data.frame(cbind("ParcelID"=unlist(gordon_modelsDT$ParcelID), "seed"=unlist(gordon_modelsDT$seed), "mod_type"=unlist(gordon_modelsDT$mod_type), "Community"=unlist(gordon_modelsDT$Community))) 

# turn NA community values into "None"/factor #7
df_gordon_models$Community= ifelse(is.na(df_gordon_models$Community), 7, df_gordon_models$Community)
sum(is.na(df_gordon_models$Community))
df_gordon_models$Community= as.factor(mapvalues(df_gordon_models$Community, c(1:13), c("Auditory", "CinguloOperc", "CinguloParietal", "Default", "DorsalAttn", "FrontoParietal", "None", "RetrosplenialTemporal", "Salience", "SMhand", "SMmouth", "VentralAttn", "Visual")))

# relevel the mod_type factor
df_gordon_models$mod_type= factor(df_gordon_models$mod_type,levels(df_gordon_models$mod_type)[c(1,4,3,2,5)])
```

# Model Selection Analysis
##Tables 
```{r descriptive tables}
tbl_community= df_gordon_models %>% group_by(Community) %>% dplyr::summarise(mod_type= n())
tbl_community$mod_type=round(tbl_community$mod_type/4,0)
kable(tbl_community, format="pandoc", caption= "# parcels per community")

tbl_cois_by_model=group_by(df_gordon_models, seed, mod_type) %>% tally %>% 
  spread(seed, n, fill = 0)
tbl_cois_by_model$sum= tbl_cois_by_model$aseg_17 + tbl_cois_by_model$aseg_18 + tbl_cois_by_model$aseg_53 + tbl_cois_by_model$aseg_54
tbl_cois_by_model$pct=round(tbl_cois_by_model$sum/1346*100, 2)
kable(tbl_cois_by_model, format="pandoc", caption= "# connections per model and seed")

tbl_cois_by_all=group_by(df_gordon_models, seed, mod_type, Community) %>% tally %>% 
  spread(Community, n, fill = 0)
kable(tbl_cois_by_all, format="pandoc", caption="# connections per community, model, and seed")

test=filter(df_gordon_models, seed=="aseg_17" & Community=="Default")
```

## Plots

### Counts
```{r plot count}

# plot remove models those best explained by the null model
df_nonull=filter(df_gordon_models, df_gordon_models$mod_type!="null model") 
pal <- wes_palette(name = "Zissou", type = "continuous")

# plot raw data sans null models
ggplot(df_nonull, aes(x=mod_type, fill=Community)) +
  geom_bar(position="dodge") +
  scale_x_discrete(labels=c("A", "N", "N & A", "N X A", "null")) +
  facet_grid(seed~.) + 
  ggtitle("Count of model types by network and seed")
```

### Proportions
```{r plot prop, include = TRUE}

df_prop= df_gordon_models %>% group_by(seed, Community=as.factor(Community), mod_type) %>% tally # removed: complete(mod_type, nesting(Community)), fill=list(n=0), this include 0% in the tallies; 
levels(df_prop$seed)=c("L hipp", "L amyg", "R hipp", "R amyg")
df_prop$comm_total=df_prop$Community
df_prop$comm_total=as.character(df_prop$comm_total)
df_prop$comm_total=mapvalues(df_prop$comm_total, c("Auditory", "CinguloOperc", "CinguloParietal", "Default", "DorsalAttn", "FrontoParietal", "None", "RetrosplenialTemporal", "Salience", "SMhand", "SMmouth", "VentralAttn", "Visual"), tbl_community$mod_type)
df_prop$comm_total=as.numeric(df_prop$comm_total)
df_prop$pct=round(df_prop$n/df_prop$comm_total*100, 2)
total_connections <- sum(tbl_community$mod_type)
df_prop$w_pct= round((df_prop$pct/100)*(df_prop$comm_total/total_connections),4)# weighted percent

df_prop_nonull=filter(df_prop, mod_type!="null model") # remove null models

#table
tbl_prop_by_model= df_prop[, c("Community","seed","mod_type", "pct")] %>% 
  spread(Community, pct, fill=0)
kable(tbl_prop_by_model, format="pandoc", caption= "prop connections per model and seed")

#table >20%
tbl_prop_by_model_20= df_prop[, c("Community","seed","mod_type", "pct")] %>%
  filter(pct>20) %>%
  spread(Community, pct, fill=0)
kable(tbl_prop_by_model_20, format="pandoc", caption= ">20% prop connections per model and seed")


# plot across ALL communities by seed region
ggplot(df_prop, aes(x=mod_type, y= pct, fill=Community)) + # fill=Community)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(labels=c("A", "N", "N & A", "N X A", "null")) + # removed "null"
  facet_grid(seed~.) + 
  ggtitle("Percent of model types by network and seed") 

# plot across ALL communities by seed region, SANS NULL MODELS
ggplot(df_prop_nonull, aes(x=mod_type, y= pct, fill=Community)) + # fill=Community)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(labels=c("abuse", "neglect", "neglect and abuse", "neglect by abuse")) + # removed "null"
  facet_grid(seed~.) + 
  xlab("Models") +
  ylab("Percentage of community connections") +
  ggtitle("Percent of model types by community and seed (no null models)")+ 
  theme(legend.text=element_text(size=7.5), legend.position="right")
    
## other ways of viewing proportioned data
ggplot(df_gordon_models,aes(x = mod_type, fill = Community)) + 
  geom_bar(position = "fill") +
  scale_x_discrete(labels=c("A", "N", "N & A", "N X A", "null")) + 
  ggtitle("proportion of communities per mod type")

df_gordon_models$mod_type= factor(df_gordon_models$mod_type,levels(df_gordon_models$mod_type)[c(5, 4, 3, 2, 1)])
df_gordon_models$mod_type=factor(df_gordon_models$mod_type,labels=c("null", "neglect by abuse", "neglect & abuse", "neglect", "abuse"))
ggplot(df_gordon_models,aes(x = Community, fill = mod_type)) + 
  geom_bar(position = "fill") +
  # scale_fill_manual(values=pal) + # special color palette! 
  scale_x_discrete(labels=c("A", "CO","CP","D", "DA","FP","NA","RT","S","h","m","VA","V")) +
  ylab("Proportion") +
  scale_fill_discrete(name="Model")+
  ggtitle("proportion of mod types per community") +
  theme(legend.position="bottom")

ggplot(df_nonull,aes(x = Community, fill = mod_type)) + 
  geom_bar(position = "fill") +
  scale_x_discrete(labels=c("A", "CO","CP","D", "DA","FP","NA","RT","S","h","m","VA","V")) +
  ggtitle("proportion of mod types per community (no null models!)")

# for reference, these are the levels
print(levels(df_gordon_models$Community))

```

```{r investigate interactions}

reg_models <- readRDS(paste0("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/regmodels.RDS"))
#reg_models$seed=gsub('(^\\w{4,9}_\\d{2,3})_.*','\\1', reg_models$coi)

# identify COI target
# reg_models$ParcelID= 
# ifelse(startsWith((gsub('aseg_\\d\\d_(.*)','\\1',reg_models$coi)), "aseg"), # if it starts with aseg
#         gsub('aseg_\\d\\d_(aseg_\\d\\d)','\\1',reg_models$coi), # then call coitarget aseg_##
#         gsub('aseg_\\d\\d_\\wh.Parcel_(.*)','\\1',reg_models$coi)) # but if not, coitarget is the Gordon #parcel number

## Match COI target with Gordon parcel #
#reg_models=merge(reg_models, parcels, by="ParcelID", all.x=TRUE)

# turn NA community values into "None"/factor #7
# reg_models$Community= ifelse(is.na(reg_models$Community), 7, reg_models$Community)

# reg_models$Community= as.factor(mapvalues(reg_models$Community, c(1:13), c("Auditory", "CinguloOperc", "CinguloParietal", "Default", "DorsalAttn", "FrontoParietal", "None", "RetrosplenialTemporal", "Salience", "SMhand", "SMmouth", "VentralAttn", "Visual")))

# SUBSET DOWN TO MODELS WITH INTERACTION

# reg_models$intercept= as.numeric(as.character(reg_models$intercept))
# reg_models$n_beta= as.numeric(as.character(reg_models$n_beta))
# reg_models$a_beta= as.numeric(as.character(reg_models$a_beta))
# reg_models$aXn_beta= as.numeric(as.character(reg_models$aXn_beta))

colnames(gordon_modelsDT)[2]="coi"

df_int= gordon_modelsDT %>% filter(mod_type=="neglect and abuse interaction model") %>% merge(reg_models,  by="coi") %>% filter(mod_type.y=="neglect_abuse_int")

load("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/gordon_coisDT.RDS")
load("/Volumes/TDS/bids_data/derivatives/Cheng_SAP/demographicsDF.csv")

i=1

adf=merge(as.data.table(subset(gordon_coisDT, coi %in% df_int$coi)), # generate "a dataframe""
                   demographicsDF,
                   by='sub',
                   allow.cartesian=T)

adf$abuse=as.factor(adf$abuse)
adf$neglect=as.factor(adf$neglect)

adf$seed=gsub('(^\\w{4,9}_\\d{2,3})_.*','\\1', adf$coi)

# identify COI target
adf$ParcelID= 
  ifelse(startsWith((gsub('aseg_\\d\\d_(.*)','\\1',adf$coi)), "aseg"), # if it starts with aseg
         gsub('aseg_\\d\\d_(aseg_\\d\\d)','\\1',adf$coi), # then call coitarget aseg_##
         gsub('aseg_\\d\\d_\\wh.Parcel_(.*)','\\1',adf$coi)) # but if not, coitarget is the Gordon #parcel number

## Match COI target with Gordon parcel #
adf=merge(adf, parcels, by="ParcelID", all.x=TRUE)

# turn NA community values into "None"/factor #7
adf$Community= ifelse(is.na(adf$Community), 7, adf$Community)

adf$Community= as.factor(mapvalues(adf$Community, c(1:13), c("Auditory", "CinguloOperc", "CinguloParietal", "Default", "DorsalAttn", "FrontoParietal", "None", "RetrosplenialTemporal", "Salience", "SMhand", "SMmouth", "VentralAttn", "Visual")))

adf$coi = as.factor(adf$coi)

# lazy rush hard coded for simplicity :()
for (i in 1:8) {
    temp= adf %>% filter(Community==unique(adf$Community)[i]) %>% subset(coi %in% df_int$coi) %>% group_by(abuse, neglect, coi) %>% summarise(mean=mean(cor), se=sd(cor)/(sqrt(nrow(adf)/77)), community=unique(adf$Community)[i])
    print(ggplot(temp, aes(x=interaction(abuse,neglect), y=mean, fill=interaction(abuse,neglect))) + 
    geom_dotplot(binaxis="y", stackdir = "center", dotsize=.5, stackratio=.5) +
    geom_line(group=temp$coi, size=.1) +
    scale_x_discrete(labels=c("None", "Abuse", "Neglect", "Neglect & Abuse")) +
    xlab("Experience") +
    ylab("Mean correlation") + 
    ggtitle(paste0("Interaction plot for the ", unique(adf$Community)[i], " network")) + 
    theme(legend.position = "none"))
}

```
