# This script generates graphs of the parameter estimates for an ROI with parametric modulators 

# LOAD PACKAGES
```{r, echo=FALSE}

packages = c("plyr", "tidyverse", "ggplot2", "gridExtra", "extrafont", "colorblindr")

# load packages, install as needed
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE) }})
#Check if the packages we need are installed, and if not, install them
if(!require(plyr)){
  install.packages('plyr',repos=osuRepo)
}
```

# Feed me.(Change the parameters)
```{r}

rm(list=ls())

#### PARAMETERS ####
subjectList= c("109", "113", "114", "115", "116", "117", "119", "120", "121", "122", "124", "125", "126", "127", "128", "129",
               "130", "131", "132", "133", "134", "135", "136", "137", "139", "140", "141", "142", "144", "145", "146", "150",
               "151", "152", "155", "156", "157", "159", "160", "162", "163", "164", "165", "167", "168", "169", "170", "171",
               "172", "173", "174", "175", "177", "179", "181", "182", "183", "184", "185", "186", "187", "188", "190", "192",
               "193", "194", "195", "196", "197")

# ROIs in the order they appear in the .csv file 
roiList= "dACC_ROI" #c("ROI1","ROI2","ROI3","ROI4","ROI5","ROI6","ROI7","ROI8")

#"craddock24_145", "craddock24_168","craddock24_172","craddock24_222","craddock24_26","craddock24_62", "craddock24_80", "craddock24_98")

# Set pmod_lowerlim:pmod_upperlim
pmodRange= 1:11

# If you tested more than 1 pmod, then all of the pmod parameters of one type should be listed, followed by all of the pmod parameters of another type. Change n to represent which pmod you'd like to change. e.g., in Cyberball, 1: inclusion pmod; 2: exclusion pmod.
pmodNames=c("Increasing_Inclusion", "Increasing_Exclusion")
totalPmods=length(pmodNames)

#### LOAD DATA ####
# Set working directory to where marsbar ROI summary time course .csv files are kept
setwd("/Volumes/TDS/nonbids_data/derivatives/fMRI/roi/cyberball/tds2_N69")#("/Volumes/TDS/nonbids_data/derivatives/fMRI/parcellations/cyb/ACC_ROIs/conj_pmod_flexi/")

# Load file - NEED TO CREATE THE SUMMARY TIME COURSE FILE!
df.raw<-read.csv("summary_F_conj_pmod_flexi.csv", header=FALSE)
```

# Organize data
```{r}
# df.raw <- df.raw %>% 
#   rename(# new = old;
#   "dACC_ROI" =  "V1")

# Label the rows and columns
colnames(df.raw)=roiList # label each column with the ROI

df.raw <- df.raw %>% 
  mutate(
    SID = rep(subjectList, length(pmodNames)),
    SID = factor(SID),
    pmod = rep(pmodNames, length(subjectList)) # for a flexi-factorial model, use length(subjectList); for a standard model, use each=length(subjectList)
         ) %>% 
  gather(roiList[], key=roi, value=param) 

df.avg = df.raw %>% 
  group_by(pmod, roi) %>% 
  summarize(mean=mean(param), sem=sd(param)/sqrt(length(subjectList)))
```


```{r set up theme black}
theme_black = function(base_size = 12, base_family = "") {
 
  theme_grey(base_size = base_size, base_family = base_family) %+replace%
 
    theme(
      # Specify axis options
      axis.line = element_blank(),  
      axis.text.x = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),
      axis.text.y = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.ticks = element_line(color = "white", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "white", margin = margin(0, 10, 0, 0)),  
      axis.title.y = element_text(size = base_size, color = "white", angle = 90, margin = margin(0, 10, 0, 0)),  
      axis.ticks.length = unit(0.3, "lines"),   
      # Specify legend options
      legend.background = element_rect(color = NA, fill = "black"),  
      legend.key = element_rect(fill = "black"),  
      legend.key.size = unit(1.2, "lines"),  
      legend.key.height = NULL,  
      legend.key.width = NULL,      
      legend.text = element_text(size = base_size, color = "white"),  
      legend.title = element_text(size = base_size, face = "bold", hjust = 0, color = "white"),  
      legend.position = "right",  
      legend.text.align = NULL,  
      legend.title.align = NULL,  
      legend.direction = "vertical",  
      legend.box = NULL, 
      # Specify panel options
      panel.background = element_rect(fill = "gray15", color  =  NA),  
      panel.border = element_rect(fill = NA, color = "white"),  
      panel.grid.major = element_line(color = "grey35"),  
      panel.grid.minor = element_line(color = "grey20"),  
      #panel.spacing = unit(0.5, "lines"),   
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text.x = element_text(size = base_size*0.8, color = "white"),  
      strip.text.y = element_text(size = base_size*0.8, color = "white",angle = -90),  
      # Specify plot options
      plot.background = element_rect(color = "black", fill = "black"),  
      plot.title = element_text(size = base_size*1.2, color = "white"),  
      panel.spacing = unit(rep(1, 4), "lines")
    )
 
}

```

# Graph pmods
```{r}

df.raw$SID = factor(df.raw$SID)

df_graph_all = data.frame(
  SID = rep(subjectList, each=(totalPmods*length(pmodRange))),
  pmod = rep(pmodNames, (length(subjectList)*length(pmodRange))),
  pmod_num = rep(pmodRange, length(subjectList)*totalPmods)
)

df_graph_all = merge(df.raw, df_graph_all, by = c("SID", "pmod"))
df_graph_all$value = df_graph_all$pmod_num*df_graph_all$param

df_graph_avg = data.frame(
  pmod = rep(pmodNames, length(pmodRange)),
  pmod_num = rep(pmodRange, totalPmods)
)

df_graph_avg = merge(df.avg, df_graph_avg, by =  "pmod")
df_graph_avg$value = df_graph_avg$pmod_num*df_graph_avg$mean

fig2 <- ggplot(df_graph_all, aes(x=pmod_num, y= value, color =pmod)) +
  geom_line(size=.5, alpha=.3, aes(group = interaction(SID,pmod)), show.legend = FALSE) + 
  geom_line(data=df_graph_avg, size = 2, aes(x=pmod_num, y= value), show.legend = FALSE) + 
  scale_y_continuous(expand = c(0, 0),
                     limits = c(-10, 5),
                     breaks = c(6, 3, 0, -3, -6, -9)) +
  scale_x_continuous(expand = c(0, 0), 
                     breaks = 1:11) +
  #labs(x=NA, y= NA) + 
  theme(text = element_text(family = "Helvetica")) +
  scale_color_manual(values = c("#660066", "#006633"),
                     name="Condition",
                    labels=c("Increasing Exclusion", "Increasing Inclusion")) + # pick colors for excl and inc
  theme_black() + 
  theme(axis.text.x = element_text(size= 16), axis.text.y = element_text(size= 16), axis.title.x = element_blank(), axis.title.y =element_blank()) 
  

colorblind_friendly <- fig2 +
  scale_color_OkabeIto() +
  scale_fill_OkabeIto()
colorblind_friendly

cvd_grid(colorblind_friendly)


# # Populate df.graph and graph each pmod for each ROI
# for (i in 1:length(roiList)) {
#   for (j in 1:totalPmods) {
#     df.graph[,j+1]=(filter(df.avg, roiList==roiList[i] & pmod== pmodNames[j])$mean) * pmodRange
#   }
#     print(ggplot(df.graph, aes(x = pmodRange)) +
#           geom_line(aes(y = Increasing_Inclusion, colour = "to participant (inclusion)"),size=1) +
#           geom_line(aes(y=Increasing_Exclusion, colour = "not to participant (exclusion)"),size=1) +
#           scale_color_manual("", breaks = c("Inclusion"," Exclusion"),values = c("Inclusion"="#9999CC","Exclusion"="#66CC99")) + 
#           scale_x_continuous(name="Number of cumulative throws", breaks=seq(-4,12,2)) +
#           scale_y_continuous(name="Beta estimate", limit = c(-2,2)) + #heme(axis.text=element_text(size=24)) + #axis.title=element_text(size=28), egend.text=element_text(size=28), legend.position="bottom") +
#           scale_size_manual(values=c(1,4)) +
#           ggtitle(roiList[i]) +
#           guides(colour = guide_legend(nrow=2,byrow=TRUE)) + 
#        theme_black() +
#        theme(legend.position = "right"))
# }

# ggplot(df.graph, aes(x = pmodRange)) +
#           geom_line(aes(y = Increasing_Inclusion, colour = "Inclusion"), size=1) +
#           geom_line(aes(y=Increasing_Exclusion, colour = "Exclusion"), size=1) +
#           scale_color_manual("", breaks = c("Inclusion"," Exclusion"), values = c("Inclusion"="#9999CC","Exclusion"="#66CC99")) + 
#           scale_x_continuous(name="Number of cumulative throws", breaks=seq(-4,12,2)) +
#           scale_y_continuous(name="Beta estimate", limit = c(-2,2)) + #heme(axis.text=element_text(size=24)) + #axis.title=element_text(size=28), egend.text=element_text(size=28), legend.position="bottom") +
#           scale_size_manual(values=c(1,4)) +
#           guides(colour = guide_legend(nrow=2,byrow=TRUE)) + 
#           theme_gray() +
#           theme(legend.position = "none")
# 
# 
#     print(ggplot((filter(df.avg, roi==roiList[i])), aes(x=pmod, y=mean, fill=pmod)) + 
#             geom_bar(stat="identity", aes(fill=pmod)) +
#             geom_errorbar(aes(ymin=mean-1.96*sem, ymax=mean+1.96*sem), width=.3) +
#             ggtitle(paste("Mean beta estimates by condition for", roiList[i], sep=" ")) +
#             guides(fill=FALSE) +
#             scale_fill_manual(breaks=c("Increasing_Inclusion", "Increasing_Exclusion"), values= c("Increasing_Inclusion"="#9999CC","Increasing_Exclusion"="#66CC99")) +
#               #breaks = c("Increasing_Inclusion","Increasing_Exclusion"),values =  + 
#             facet_grid(.~roi) +
#             labs(x="Conditions", y="Mean beta estimates"))
# }

```
            