---
title: "FreeSurfer Stats"
author: "Kate"
date: "26 April 2017"
output: html_document
---

# Begin script

Load required packages
```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("lme4", "nlme", "ggplot2", "zoo","dplyr", "tidyr", "knitr",
              "parallel", "data.table", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Extract FreeSurfer preprocessing stats
```{r Extract and plot run times, echo=TRUE}
# Set directory
#freesurfer_subjects="/Volumes/TDS/ppcd_nii/sMRI/subjects/"
freesurfer_subjects="/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/freesurfer6/"
# create sub list based on folders within the freesurfer subjects folder
subs<-list.files(path = freesurfer_subjects, pattern = "sub")
# extract info
extract_freesurfer_runinfo= function(sub){
  if (nrow(read.csv(paste0(freesurfer_subjects,sub,"/scripts/recon-all.done")))>1){
    log<-read.csv(paste0(freesurfer_subjects,sub,"/scripts/recon-all-status.log"))
    finaloutput<-tail(log,1)
    recon_done<-read.csv(paste0(freesurfer_subjects,sub,"/scripts/recon-all.done"))
    runtime<-recon_done %>% filter(grepl("RUNTIME",.[[1]]))
    runtime<-as.character(runtime[[1]])
    runtime<-substring(runtime,first=15,last=(nchar(runtime)))
    cbind(sub,runtime,finaloutput)
    } else {
      runtime<-"NA"
      status.file.for.recon.all<-"NA"
      cbind(sub,runtime,status.file.for.recon.all)
    }
}
outputlist<-lapply(subs,extract_freesurfer_runinfo)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(runtime=as.numeric(levels(runtime))[runtime])
times <- ggplot((output.df %>% select(-status.file.for.recon.all)),
                aes(x=sub, y=runtime, fill=runtime))
times + geom_bar(colour="black", stat="identity") 
```


Plot structural MRI info
```{r Extract and plot structural MRI info, echo=TRUE}
# Set directory
#freesurfer_subjects="/Volumes/TDS/ppcd_nii/sMRI/subjects/"
freesurfer_subjects="/Volumes/psych-cog/dsnlab/TAG/TAG_BIDS/derivatives/freesurfer6/"
# create sub list based on folders within the freesurfer subjects folder
subs<-list.files(path = freesurfer_subjects, pattern = "sub")
# extract info
asegcolnames<-c("Index","SegId","NVoxels","Volume_mm3","StructName","normMean","normStdDev","normMin","normMax","normRange")
extract_vols= function(sub){
  if (file.exists((paste0(freesurfer_subjects,sub,"/stats/aseg.stats")))){
  aseg<-read.table(paste0(freesurfer_subjects,sub,"/stats/aseg.stats"))
  colnames(aseg)<-asegcolnames
  amygdala_vol<-sum(aseg %>% filter(grepl("Left-Amygdala",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Amygdala",StructName)) %>% select(Volume_mm3))
  caudate_vol<-sum(aseg %>% filter(grepl("Left-Caudate",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Caudate",StructName)) %>% select(Volume_mm3))
  hippocampus_vol<-sum(aseg %>% filter(grepl("Left-Hippocampus",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Hippocampus",StructName)) %>% select(Volume_mm3))
  nacc_vol<-sum(aseg %>% filter(grepl("Left-Accumbens-area",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Accumbens-area",StructName)) %>% select(Volume_mm3))
  thalamus_vol<-sum(aseg %>% filter(grepl("Left-Thalamus-Proper",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Thalamus-Proper",StructName)) %>% select(Volume_mm3))
  putamen_vol<-sum(aseg %>% filter(grepl("Left-Putamen",StructName)) %>% select(Volume_mm3),
                    aseg %>% filter(grepl("Right-Putamen",StructName)) %>% select(Volume_mm3))
  cbind(sub,amygdala_vol,caudate_vol,hippocampus_vol,nacc_vol,thalamus_vol,putamen_vol)}
}
outputlist<-lapply(subs,extract_vols)
output.df<-as.data.frame(do.call(rbind,outputlist)) %>% 
  mutate(amygdala_vol=as.numeric(levels(amygdala_vol))[amygdala_vol],
         caudate_vol=as.numeric(levels(caudate_vol))[caudate_vol],
         nacc_vol=as.numeric(levels(nacc_vol))[nacc_vol],
         hippocampus_vol=as.numeric(levels(hippocampus_vol))[hippocampus_vol],
         thalamus_vol=as.numeric(levels(thalamus_vol))[thalamus_vol],
         putamen_vol=as.numeric(levels(putamen_vol))[putamen_vol])
long<-gather(output.df, "sub", "parcel", 2:7)
colnames(long)<-c("sub","parcel","volume")
subcortical_volumes<-ggplot(long, aes(x=parcel, y=volume, color=parcel)) +
  geom_violin(trim=FALSE)
subcortical_volumes
```