---
title: "CybDescriptives"
author: "Nandi"
date: "September 21, 2017"
output: html_document
---

#Load data
```{r}
subDir <- '/projects/dsnlab/tds/TDS_scripts/fMRI/fx/shell/schedule_spm_jobs/cyb/tds2'
sub <- read.csv(paste0(subDir,'/subject_list_fx.txt'), header=F)
colnames(sub)[1] <- "SID"

demoDir <- '/Volumes/psy-ctn/psy-ctn/TDS/behavior/CyberBall/'
demo <- read.csv(paste0(demoDir,'tds2_demographics/Cyb_demo.csv'))

rsq <- read.csv(paste0(demoDir,'tds2_rsq_imputed_centered.csv'))
nts <- read.csv(paste0(demoDir,'nts.csv'))

```

#Merge data and calculate age
```{r}
demo <- merge(sub,demo,by="SID")
demo$Gender <- as.factor(demo$Gender)
demo$ScanDate <- as.Date(demo$ScanDate.1, format='%m/%d/%y')
demo$DOB <- as.Date(demo$DOB, format='%m/%d/%y')
demo$Age <- as.numeric((demo$ScanDate - demo$DOB)/365)
demo$Age_c <- (demo$Age) - (mean(demo$Age))
demo$Age_c_quad <- (demo$Age_c*demo$Age_c)
```

#Summary statistics
```{r}
mean(demo$Age) #14.22 
sd(demo$Age) #1.53

summary(demo$Gender) #0:33 1:36

temp <- merge(demo, rsq_exp, by = "SID")
temp <- merge(temp, nts, by = "SID")
temp$exp <- as.numeric(temp$exp)
cor(temp$Age, temp$exp)
cor(temp$Age, temp$NTS_total_score_score, use = "complete.obs")

plot(temp$Age, temp$exp)
plot(temp$Age, temp$NTS_total_score_score)

```

#Write statistics
```{r}
#write.csv(demo, paste0(demoDir,'/Cyb_centeredAge.csv', row.names=F)