---
title: "graphAnyROI_pmods"
author: "TC"
date: "July 7, 2016"
output: html_document
---

# This script generates graphs of the parameter estimates for an ROI with parametric modulators 

# LOAD PACKAGES
```{r, echo=FALSE}
osuRepo<-'http://ftp.osuosl.org/pub/cran/'

#Check if the packages we need are installed, and if not, install them
if(!require(plyr)){
  install.packages('plyr',repos=osuRepo)
}
library(plyr)

if(!require(dplyr)){
  install.packages('dplyr',repos=osuRepo)
}
library(dplyr)

if(!require(tidyr)){
  install.packages('tidyr',repos=osuRepo)
}
library(tidyr)

if(!require(ggplot2)){
  install.packages('data.table',repos=osuRepo)
}
library(ggplot2)
```

# Feed me.(Change the parameters)
```{r}
rm(list=ls())

#### PARAMETERS ####
subjectList= c("113","114","115","116","117","119","121","125","126","127","128","129","130","131","132","133","134","135","136","137","139","140","141","142","144","145","146","150","151","152","155","156","157","158","159","160","161","162","163","164","165","167","168","169","170","171","172","173","174","175","177","179","181","182","183","184","185","186","187","188","189","190","192","193","196")

# ROIs in the order they appear in the .csv file 
roiList=c("-8 6 38")

# Set pmod_lowerlim:pmod_upperlim
pmodRange= -4:7

# If you tested more than 1 pmod, then all of the pmod parameters of one type should be listed, followed by all of the pmod parameters of another type. Change n to represent which pmod you'd like to change. e.g., in Cyberball, 1: inclusion pmod; 2: exclusion pmod.
totalPmods=2
pmodNames=c("Increasing_Inclusion", "Increasing_Exclusion")

#### LOAD DATA ####
# Set working directory to where marsbar ROI summary time course .csv files are kept
setwd("/Volumes/research/tds/fMRI/analysis/roi/cyb/cyb_events/noage_covariate/catch_meanCpmod_linear_w190/F_pmod/meta")

# Load file - NEED TO CREATE THE SUMMARY TIME COURSE FILE!
df.raw<-read.csv("summary_meta_AdolNonClin.csv", header=FALSE)
```

# Organize data
```{r}
# Label the rows and columns
colnames(df.raw)=roiList # label each column with the ROI
df.raw$SID=subjectList # add the list of SIDs
df.raw=df.raw[,c("SID", roiList)] # rearrange with SIDs on the left

# Calculate parameter estimate averages per ROI per pmod
df.avg=data.frame(matrix(rep(NA, length(roiList)*totalPmods), nrow=totalPmods), row.names=pmodNames)
colnames(df.avg)=c(roiList)

for (i in 1:length(roiList)){
  for (j in 1:totalPmods){
    df.avg[j,i]=mean(df.raw[(j-1)+1:length(subjectList)*j,i+1], na.rm=TRUE)
  }
}
```

# Graph pmods
```{r}

# Set up a null dataframe called df.graph for summarizing plot parameters
df.graph=as.data.frame(matrix(rep(NA, length(pmodRange)*(totalPmods+1)), nrow=length(pmodRange), ncol=(totalPmods+1)))
colnames(df.graph)=c("pmodRange",pmodNames)
df.graph$pmodRange=pmodRange

# Populate df.graph and graph each pmod for each ROI
for (i in 1:length(roiList)){
    for (j in 1:totalPmods) {
    df.graph[,j+1]=df.avg[j,i]*pmodRange
    print(ggplot(df.graph, aes_string(x=pmodRange, y=pmodNames[j])) +
      geom_point(shape=1) +
      geom_smooth() +
      ggtitle(paste("Graph of", pmodNames[j], "for", roiList[i], sep=" ")))
    }
}

#Note: Add geom_smooth(aes(x=pmodRange, y=[insert pmodName]) if you want to plot multiple pmods on the same plot
```
